# https://hub.docker.com/_/alpine
FROM alpine:3.16

# install pip
RUN apk add --update-cache \
    py3-pip \
  && rm -rf /var/cache/apk/*

# create app directory
WORKDIR /code

# bundle app source
COPY . .

# install required packages
RUN pip install -r requirements.txt

# our application will listen on port 5000 inside the container
EXPOSE 5000

# run the application
CMD ["python3", "app.py"]