namePrefix: prod-
commonLabels:
  environment: production
resources:
- ../../base
patchesStrategicMerge:
- image.yaml
- replica_count.yaml
configMapGenerator:
- name: index
  behavior: replace
  files:
  - configs/index.html
