version: '3'
 
services:
  db:
    # https://hub.docker.com/_/mysql
    image: mysql:8.0.30 
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: my_secret_password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: WordPress
    volumes:
      - dbdata:/var/lib/mysql
  
  # https://hub.docker.com/_/wordpress
  wordpress:
    depends_on:
      - db
    image: wordpress:6.0.2
    ports:
      - 80:80
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: WordPress
    volumes:
      - wordpress:/var/www/html
  
  # https://hub.docker.com/r/phpmyadmin/phpmyadmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2.0-fpm-alpine
    container_name: pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8080:80

volumes:
  dbdata: {}
  wordpress: {}
